//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUDTestProgram {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUDTestProgram.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   delete {0} where {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES where TABLE_CATALOG = &apos;{0}&apos; and TABLE_NAME=&apos;{1}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string existTable {
            get {
                return ResourceManager.GetString("existTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   insert into {0} values ({1})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string insert {
            get {
                return ResourceManager.GetString("insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0};
        ///
        ///{1};
        ///
        ///{2};과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string saveQuery {
            get {
                return ResourceManager.GetString("saveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select top(100)* FROM (select &apos;&apos; as &apos;상태&apos; ) as A right outer join [{0}].[dbo].[{1}]  on 1=1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectAll {
            get {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME=&apos;{0}&apos; 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectPK {
            get {
                return ResourceManager.GetString("selectPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select {0} from {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectPKList {
            get {
                return ResourceManager.GetString("selectPKList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string selectTableInfo {
            get {
                return ResourceManager.GetString("selectTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   update {0} set {1} where {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string udpate {
            get {
                return ResourceManager.GetString("udpate", resourceCulture);
            }
        }
    }
}
